language: node_js
node_js:
  - v8

addons:
  code_climate:

notifications:
  email:
    - alberto.souza.dev@gmail.com

after_success:
- npm install coveralls
- npm run coverage
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js